---
- hosts: localhost
  tasks:
    - name: load config file
      include_vars:
        file: "{{ config_file }}"
        name: config
    - name: create stack
      cloudformation:
        stack_name: "{{ ((config_file | basename ) | splitext)[0] }}"
        state: "present"
        region: "ap-southeast-2"
        template: "cloudformation.yaml"
        template_parameters: '{{ config.Parameters }}'
        tags: '{{ config.Tags }}'
        validate_certs: no
    - name: crate or update dns
        shell: Route53toELB.sh "{{ ((config_file | basename ) | splitext)[0] }}" '{{ config.Parameters }}'>> Route53toELB.log
        args:
          chdir: scripts/