---
AWSTemplateFormatVersion: '2010-09-09'
Description: Basic Build Box
Parameters:
  Environment:
    Type: String
    Default: nonprod

  # EC2 data
  InstanceProfile:
    Type: String
    Default: HIPBaseInstanceProfile
  AMIId:
    Type: String
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Type: String
    Default: t2.medium
  VPC:
    Type: AWS::EC2::VPC::Id
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  TagOwner:
    Type: String
  TagCostCentre:
    Type: String 

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupName: !Sub ${AWS::StackName}-${SecurityGroupName}
      GroupDescription: !Sub "Security group for ${SecurityGroupName}"
      SecurityGroupIngress:
      - CidrIp: 10.0.0.0/8
        FromPort: '443'
        ToPort: '443'
        IpProtocol: "-1"
      - CidrIp: 10.0.0.0/8
        FromPort: '22'
        ToPort: '22'
        IpProtocol: "-1"


  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref AMIId
      IamInstanceProfile: !Ref InstanceProfile
      SecurityGroups:
      - Ref: SecurityGroup
      InstanceType: !Ref InstanceType
      BlockDeviceMappings:
      - DeviceName: "/dev/sdf"
        Ebs:
          VolumeSize: 20
          VolumeType: gp2
          Encrypted: true
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -ex
            exec >> /var/log/user-data.log
            exec 2>&1
            source /etc/profile.d/proxy.sh
            # 
            # updated installed packages
            yum -y update 
            yum update aws-cfn-bootstrap
            #
            # Signal completion
            echo "Issuing cfn-signal"
            /bin/cfn-signal -e $? --stack ${AWS::StackName} --resource AutoscalingGroup --region ${AWS::Region}


  AutoscalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref Subnets
      LaunchConfigurationName: !Ref LaunchConfiguration
      MinSize: '0'
      MaxSize: '2'
      DesiredCapacity: '1'
      Tags:
        - Key: PowerMgt
          Value: MBHSTOP
          PropagateAtLaunch: true
        - Key: Owner
          Value: !Ref TagOwner
          PropagateAtLaunch: true
        - Key: CostCentre
          Value: !Ref TagCostCentre
          PropagateAtLaunch: true
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: '1'
        MaxBatchSize: '1'
        WaitOnResourceSignals: true
        PauseTime: PT20M
        SuspendProcesses:
        - ScheduledActions
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT20M





